#!/usr/bin/php
<?php

require_once __DIR__ . '/includes/db.inc.php';
require_once __DIR__ . '/includes/src.inc.php';

if ($argc <> 2) {
	echo "Syntax: $argv[0] <line>\n";
	exit(2);
}

if (isset($stam_cfg['weblog_host']) && !empty($stam_cfg['weblog_host'])) {
	db_close();

	$weblog_host = $stam_cfg['weblog_host'];
	$weblog_user = $stam_cfg['weblog_user'];
	$weblog_pass = $stam_cfg['weblog_pass'];
	$weblog_base = $stam_cfg['weblog_base'];

	if (!db_connect($weblog_host, $weblog_user, $weblog_pass)) {
		fwrite(STDERR, "Weblog MySQL connect error\n");
		exit(2);
	}

	if (!db_select_db($weblog_base)) {
		fwrite(STDERR, "Weblog MySQL DB select error\n");
		weblog_close();
		exit(2);
	}

	$ent = rtrim($argv[1]);

	if (isset($stam_cfg['weblog_password']) && !empty($stam_cfg['weblog_password'])) {
		$iv = 'AAAAAAAAAAAAAAAA';
		$ent = base64_encode(openssl_encrypt($ent, 'AES-128-CBC', $stam_cfg['weblog_password'], OPENSSL_RAW_DATA, $iv));
	}

	$x = db_query("INSERT INTO stam_weblog (ts, inp) VALUES (
		NOW(),
		'".db_real_escape_string($ent)."'
		)");
	if (!$x) {
		fwrite(STDERR, db_error()."\n");
		db_close();
		exit(1);
	}

	$id = db_insert_id();
	if (!$id) {
		fwrite(STDERR, "Error: Could not insert\n");
		db_close();
		exit(1);
	}

	echo green("Weblog written <$id> <$ent>!\n");
}

# ---

function green($txt) {
	return "\033[1;32;40m".$txt."\033[0m";
}
